[env]
in = "src/ghost.c src/frames.c"
out = "ghost"
bin = "bin"
ver = "-std=c99"
args = "-O3 -march=native -flto -ffast-math"

[project]
name = "ghost"
version = "0.0.1"

[tasks]
clean.script = ["rm -rf %{env.bin}",  "mkdir %{env.bin}"]
build.script = "clang %{env.args} %{env.ver} %{env.in} -o %{env.bin}/%{env.out}"

[tasks.build.cache]
path = "src"
target = ["bin/ghost"]

[tasks.run]
depends = ["clean", "build"]
script = "./%{env.bin}/%{env.out}"
